language: r
r: release
sudo: required
warnings_are_errors: false

matrix:
  include:
    - os: osx      
      osx_image: xcode8.2
    - os: linux

addons:
  apt:
    sources:
      - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ubuntu-toolchain-r-test ; fi

packages:
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gcc-4.9 ; fi
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then g++-4.9 ; fi
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then unixodbc-dev ; fi

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    
install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; sudo chown -R $(whoami) /usr/local/share/man/man7 ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install unixodbc ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];  Rscript -e 'install.packages("devtools", repos = "http://cran.rstudio.com")' ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; Rscript -e 'install.packages(c("caret","data.table","doParallel","e1071"), repos = "http://cran.rstudio.com")' ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; Rscript -e 'install.packages(c("grpreg","lme4","lubridate","pROC"), repos = "http://cran.rstudio.com")' ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; Rscript -e 'install.packages(c("ranger","ROCR","testthat","RODBC"), repos = "http://cran.rstudio.com")' ; fi
