# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

warnings_are_errors: false

matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      r: release
      sudo: required

addons:
  apt:
    packages:
      - unixODBC
      - unixodbc-dev
      
r_binary_packages: RODBC


  
