language: r
r: release
sudo: required
      
os:
  - osx

r_binary_packages: RODBC 
    
install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install unixodbc ; fi